.TH "_GPU_DEVICE" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GPU_DEVICE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wglext\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DWORD \fBcb\fP"
.br
.ti -1c
.RI "CHAR \fBDeviceName\fP [32]"
.br
.ti -1c
.RI "CHAR \fBDeviceString\fP [128]"
.br
.ti -1c
.RI "DWORD \fBFlags\fP"
.br
.ti -1c
.RI "RECT \fBrcVirtualScreen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 457 of file wglext\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "DWORD _GPU_DEVICE::cb"

.PP
Definition at line 458 of file wglext\&.h\&.
.SS "CHAR _GPU_DEVICE::DeviceName[32]"

.PP
Definition at line 459 of file wglext\&.h\&.
.SS "CHAR _GPU_DEVICE::DeviceString[128]"

.PP
Definition at line 460 of file wglext\&.h\&.
.SS "DWORD _GPU_DEVICE::Flags"

.PP
Definition at line 461 of file wglext\&.h\&.
.SS "RECT _GPU_DEVICE::rcVirtualScreen"

.PP
Definition at line 462 of file wglext\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
