.TH "SSWC/src/App.h" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SSWC/src/App.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CSpice/CSpice\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iomanip>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApp\fP"
.br
.ti -1c
.RI "struct \fBApp::DefaultUnits\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBREF_FRAME_DEFAULT\fP   \fBFrame::J2000\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define REF_FRAME_DEFAULT   \fBFrame::J2000\fP"

.PP
Definition at line 11 of file App\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
