.TH "App::DefaultUnits" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App::DefaultUnits \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <App\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLengthUnit\fP \fBlengthUnit\fP"
.br
.ti -1c
.RI "\fBVelocityUnit\fP \fBvelocityUnit\fP"
.br
.ti -1c
.RI "\fBMassUnit\fP \fBmassUnit\fP"
.br
.ti -1c
.RI "\fBAccelerationUnit\fP \fBaccUnit\fP"
.br
.ti -1c
.RI "\fBGravitationalParameterUnit\fP \fBgmUnit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file App\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAccelerationUnit\fP App::DefaultUnits::accUnit"

.PP
Definition at line 28 of file App\&.h\&.
.SS "\fBGravitationalParameterUnit\fP App::DefaultUnits::gmUnit"

.PP
Definition at line 29 of file App\&.h\&.
.SS "\fBLengthUnit\fP App::DefaultUnits::lengthUnit"

.PP
Definition at line 25 of file App\&.h\&.
.SS "\fBMassUnit\fP App::DefaultUnits::massUnit"

.PP
Definition at line 27 of file App\&.h\&.
.SS "\fBVelocityUnit\fP App::DefaultUnits::velocityUnit"

.PP
Definition at line 26 of file App\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
