.TH "SSWC/src/GL/ARB_Multisample.h" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SSWC/src/GL/ARB_Multisample.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'wglext\&.h'\fP
.br
\fC#include 'glext\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCHECK_FOR_MULTISAMPLE\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBInitMultisample\fP (HINSTANCE hInstance, HWND hWnd, PIXELFORMATDESCRIPTOR pfd)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBarbMultisampleSupported\fP"
.br
.ti -1c
.RI "\fBint\fP \fBarbMultisampleFormat\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CHECK_FOR_MULTISAMPLE   1"

.PP
Definition at line 21 of file ARB_Multisample\&.h\&.
.SH "Function Documentation"
.PP 
.SS "bool InitMultisample (HINSTANCEhInstance, HWNDhWnd, PIXELFORMATDESCRIPTORpfd)"

.PP
Definition at line 65 of file ARB_Multisample\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBint\fP arbMultisampleFormat"

.PP
Definition at line 22 of file ARB_Multisample\&.cpp\&.
.SS "bool arbMultisampleSupported"

.PP
Definition at line 21 of file ARB_Multisample\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
