.TH "CosmoPoint" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CosmoPoint \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CosmoPoint\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCosmoPoint\fP ()"
.br
.ti -1c
.RI "\fB~CosmoPoint\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBInitialize\fP (const \fBVector3\fP &\fBposition\fP=0, const \fBVector3\fP &\fBvelocity\fP=0, const \fBstd::string\fP \fBname\fP='', \fBstd::string\fP \fBdescription\fP='')"
.br
.ti -1c
.RI "\fBCosmoPoint\fP & \fBoperator=\fP (const \fBCosmoPoint\fP &rPoint)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVector3\fP \fBposition\fP"
.br
.ti -1c
.RI "\fBVector3\fP \fBvelocity\fP"
.br
.ti -1c
.RI "\fBstd::string\fP \fBname\fP"
.br
.ti -1c
.RI "\fBstd::string\fP \fBdescription\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file CosmoPoint\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CosmoPoint::CosmoPoint ()"

.PP
Definition at line 4 of file CosmoPoint\&.cpp\&.
.SS "CosmoPoint::~CosmoPoint ()"

.PP
Definition at line 13 of file CosmoPoint\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP CosmoPoint::Initialize (const \fBVector3\fP &position = \fC0\fP, const \fBVector3\fP &velocity = \fC0\fP, const \fBstd::string\fPname = \fC''\fP, \fBstd::string\fPdescription = \fC''\fP)"

.PP
Definition at line 17 of file CosmoPoint\&.cpp\&.
.SS "\fBCosmoPoint\fP& CosmoPoint::operator= (const \fBCosmoPoint\fP &rPoint)"

.SH "Member Data Documentation"
.PP 
.SS "\fBstd::string\fP CosmoPoint::description"

.PP
Definition at line 10 of file CosmoPoint\&.h\&.
.SS "\fBstd::string\fP CosmoPoint::name"

.PP
Definition at line 9 of file CosmoPoint\&.h\&.
.SS "\fBVector3\fP CosmoPoint::position"

.PP
Definition at line 7 of file CosmoPoint\&.h\&.
.SS "\fBVector3\fP CosmoPoint::velocity"

.PP
Definition at line 8 of file CosmoPoint\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
