.TH "SSWC/src/CSpice/Date.h" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SSWC/src/CSpice/Date.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'CSpiceCore\&.h'\fP
.br
\fC#include '\&.\&./Math/Quantity\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDate\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFORMAT_STRING_BUFFER\fP   1024"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FORMAT_STRING_BUFFER   1024"

.PP
Definition at line 8 of file Date\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
