.TH "Frame::FrameInfo" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Frame::FrameInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Frame\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBcenterId\fP"
.br
.ti -1c
.RI "\fBFrameType\fP \fBframeType\fP"
.br
.ti -1c
.RI "long \fBclassId\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file Frame\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "long Frame::FrameInfo::centerId"

.PP
Definition at line 28 of file Frame\&.h\&.
.SS "long Frame::FrameInfo::classId"

.PP
Definition at line 30 of file Frame\&.h\&.
.SS "\fBFrameType\fP Frame::FrameInfo::frameType"

.PP
Definition at line 29 of file Frame\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
