.TH "SSWC/src/ft2build.h" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SSWC/src/ft2build.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <freetype/config/ftheader\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFT_CONFIG_OPTIONS_H\fP   <\fBftoption\&.h\fP>"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FT_CONFIG_OPTIONS_H   <\fBftoption\&.h\fP>"

.PP
Definition at line 33 of file ft2build\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
