.TH "GL_WindowInit" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GL_WindowInit \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Program\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBApplication\fP * \fBapplication\fP"
.br
.ti -1c
.RI "char * \fBtitle\fP"
.br
.ti -1c
.RI "\fBint\fP \fBwidth\fP"
.br
.ti -1c
.RI "\fBint\fP \fBheight\fP"
.br
.ti -1c
.RI "\fBint\fP \fBbitsPerPixel\fP"
.br
.ti -1c
.RI "\fBBOOL\fP \fBisFullScreen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file Program\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBApplication\fP* GL_WindowInit::application"

.PP
Definition at line 15 of file Program\&.h\&.
.SS "\fBint\fP GL_WindowInit::bitsPerPixel"

.PP
Definition at line 19 of file Program\&.h\&.
.SS "\fBint\fP GL_WindowInit::height"

.PP
Definition at line 18 of file Program\&.h\&.
.SS "\fBBOOL\fP GL_WindowInit::isFullScreen"

.PP
Definition at line 20 of file Program\&.h\&.
.SS "char* GL_WindowInit::title"

.PP
Definition at line 16 of file Program\&.h\&.
.SS "\fBint\fP GL_WindowInit::width"

.PP
Definition at line 17 of file Program\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
