.TH "GL_Window" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GL_Window \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Program\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKeys\fP * \fBkeys\fP"
.br
.ti -1c
.RI "HWND \fBhWnd\fP"
.br
.ti -1c
.RI "\fBHDC\fP \fBhDC\fP"
.br
.ti -1c
.RI "\fBHGLRC\fP \fBhRC\fP"
.br
.ti -1c
.RI "\fBGL_WindowInit\fP \fBinit\fP"
.br
.ti -1c
.RI "\fBBOOL\fP \fBisVisible\fP"
.br
.ti -1c
.RI "DWORD \fBlastTickCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file Program\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBHDC\fP GL_Window::hDC"

.PP
Definition at line 26 of file Program\&.h\&.
.SS "\fBHGLRC\fP GL_Window::hRC"

.PP
Definition at line 27 of file Program\&.h\&.
.SS "HWND GL_Window::hWnd"

.PP
Definition at line 25 of file Program\&.h\&.
.SS "\fBGL_WindowInit\fP GL_Window::init"

.PP
Definition at line 28 of file Program\&.h\&.
.SS "\fBBOOL\fP GL_Window::isVisible"

.PP
Definition at line 29 of file Program\&.h\&.
.SS "\fBKeys\fP* GL_Window::keys"

.PP
Definition at line 24 of file Program\&.h\&.
.SS "DWORD GL_Window::lastTickCount"

.PP
Definition at line 30 of file Program\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
