.TH "GLUI_StaticText" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLUI_StaticText \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glui\&.h>\fP
.PP
Inherits \fBGLUI_Control\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBset_text\fP (const char *\fBtext\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdraw\fP (\fBint\fP \fBx\fP, \fBint\fP \fBy\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdraw_text\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBupdate_size\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBerase_text\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBGLUI_StaticText\fP (\fBGLUI_Node\fP *\fBparent\fP, const char *\fBname\fP)"
.br
.ti -1c
.RI "\fBGLUI_StaticText\fP (\fBvoid\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBcommon_init\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1951 of file glui\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GLUI_StaticText::GLUI_StaticText (\fBGLUI_Node\fP *parent, const char *name)"

.SS "GLUI_StaticText::GLUI_StaticText (\fBvoid\fP)\fC [inline]\fP"

.PP
Definition at line 1961 of file glui\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP GLUI_StaticText::common_init (\fBvoid\fP)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 1964 of file glui\&.h\&.
.SS "\fBvoid\fP GLUI_StaticText::draw (\fBint\fPx, \fBint\fPy)\fC [virtual]\fP"

.PP
Implements \fBGLUI_Control\fP\&.
.SS "\fBvoid\fP GLUI_StaticText::draw_text (\fBvoid\fP)"

.SS "\fBvoid\fP GLUI_StaticText::erase_text (\fBvoid\fP)"

.SS "\fBvoid\fP GLUI_StaticText::set_text (const char *t)\fC [virtual]\fP"
Writes live variable 
.PP
Reimplemented from \fBGLUI_Control\fP\&.
.SS "\fBvoid\fP GLUI_StaticText::update_size (\fBvoid\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBGLUI_Control\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
