.TH "GLUI_List_Item" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLUI_List_Item \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glui\&.h>\fP
.PP
Inherits \fBGLUI_Node\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGLUI_String\fP \fBtext\fP"
.br
.ti -1c
.RI "\fBint\fP \fBid\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 2080 of file glui\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP GLUI_List_Item::id"

.PP
Definition at line 2084 of file glui\&.h\&.
.SS "\fBGLUI_String\fP GLUI_List_Item::text"

.PP
Definition at line 2083 of file glui\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
