.TH "GLUI_Rotation" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLUI_Rotation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glui\&.h>\fP
.PP
Inherits \fBGLUI_Mouse_Interaction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBiaction_mouse_down_handler\fP (\fBint\fP local_x, \fBint\fP local_y)"
.br
.ti -1c
.RI "\fBint\fP \fBiaction_mouse_up_handler\fP (\fBint\fP local_x, \fBint\fP local_y, bool inside)"
.br
.ti -1c
.RI "\fBint\fP \fBiaction_mouse_held_down_handler\fP (\fBint\fP local_x, \fBint\fP local_y, bool inside)"
.br
.ti -1c
.RI "\fBint\fP \fBiaction_special_handler\fP (\fBint\fP key, \fBint\fP modifiers)"
.br
.ti -1c
.RI "\fBvoid\fP \fBiaction_init\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBiaction_draw_active_area_persp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBiaction_draw_active_area_ortho\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBiaction_dump\fP (FILE *output)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetup_texture\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetup_lights\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdraw_ball\fP (float radius)"
.br
.ti -1c
.RI "\fBvoid\fP \fBinit_ball\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBreset\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "bool \fBneeds_idle\fP (\fBvoid\fP) const "
.br
.ti -1c
.RI "\fBvoid\fP \fBidle\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcopy_float_array_to_ball\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcopy_ball_to_float_array\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_spin\fP (float damp_factor)"
.br
.ti -1c
.RI "\fBGLUI_Rotation\fP (\fBGLUI_Node\fP *\fBparent\fP, const char *\fBname\fP, float *live_var=NULL, \fBint\fP \fBid\fP=-1, \fBGLUI_CB\fP \fBcallback\fP=\fBGLUI_CB\fP())"
.br
.ti -1c
.RI "\fBGLUI_Rotation\fP (\fBvoid\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Arcball * \fBball\fP"
.br
.ti -1c
.RI "GLUquadricObj * \fBquadObj\fP"
.br
.ti -1c
.RI "bool \fBcan_spin\fP"
.br
.ti -1c
.RI "bool \fBspinning\fP"
.br
.ti -1c
.RI "float \fBdamping\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBcommon_init\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An onscreen rotation controller--allows the user to interact with a 3D rotation via a spaceball-like interface\&. 
.PP
Definition at line 2436 of file glui\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GLUI_Rotation::GLUI_Rotation (\fBGLUI_Node\fP *parent, const char *name, float *live_var = \fCNULL\fP, \fBint\fPid = \fC-1\fP, \fBGLUI_CB\fPcallback = \fC\fBGLUI_CB\fP()\fP)"

.SS "GLUI_Rotation::GLUI_Rotation (\fBvoid\fP)\fC [inline]\fP"

.PP
Definition at line 2475 of file glui\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP GLUI_Rotation::common_init ()\fC [protected]\fP"

.SS "\fBvoid\fP GLUI_Rotation::copy_ball_to_float_array (\fBvoid\fP)"

.SS "\fBvoid\fP GLUI_Rotation::copy_float_array_to_ball (\fBvoid\fP)"

.SS "\fBvoid\fP GLUI_Rotation::draw_ball (floatradius)"

.SS "\fBvoid\fP GLUI_Rotation::iaction_draw_active_area_ortho (\fBvoid\fP)\fC [virtual]\fP"

.PP
Implements \fBGLUI_Mouse_Interaction\fP\&.
.SS "\fBvoid\fP GLUI_Rotation::iaction_draw_active_area_persp (\fBvoid\fP)\fC [virtual]\fP"

.PP
Implements \fBGLUI_Mouse_Interaction\fP\&.
.SS "\fBvoid\fP GLUI_Rotation::iaction_dump (FILE *output)\fC [virtual]\fP"

.PP
Implements \fBGLUI_Mouse_Interaction\fP\&.
.SS "\fBvoid\fP GLUI_Rotation::iaction_init (\fBvoid\fP)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBGLUI_Mouse_Interaction\fP\&.
.PP
Definition at line 2448 of file glui\&.h\&.
.SS "\fBint\fP GLUI_Rotation::iaction_mouse_down_handler (\fBint\fPlocal_x, \fBint\fPlocal_y)\fC [virtual]\fP"

.PP
Implements \fBGLUI_Mouse_Interaction\fP\&.
.SS "\fBint\fP GLUI_Rotation::iaction_mouse_held_down_handler (\fBint\fPlocal_x, \fBint\fPlocal_y, boolinside)\fC [virtual]\fP"

.PP
Implements \fBGLUI_Mouse_Interaction\fP\&.
.SS "\fBint\fP GLUI_Rotation::iaction_mouse_up_handler (\fBint\fPlocal_x, \fBint\fPlocal_y, boolinside)\fC [virtual]\fP"

.PP
Implements \fBGLUI_Mouse_Interaction\fP\&.
.SS "\fBint\fP GLUI_Rotation::iaction_special_handler (\fBint\fPkey, \fBint\fPmodifiers)\fC [virtual]\fP"

.PP
Implements \fBGLUI_Mouse_Interaction\fP\&.
.SS "\fBvoid\fP GLUI_Rotation::idle (\fBvoid\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBGLUI_Control\fP\&.
.SS "\fBvoid\fP GLUI_Rotation::init_ball (\fBvoid\fP)"

.SS "bool GLUI_Rotation::needs_idle (\fBvoid\fP) const\fC [virtual]\fP"

.PP
Reimplemented from \fBGLUI_Control\fP\&.
.SS "\fBvoid\fP GLUI_Rotation::reset (\fBvoid\fP)"

.SS "\fBvoid\fP GLUI_Rotation::set_spin (floatdamp_factor)"

.SS "\fBvoid\fP GLUI_Rotation::setup_lights (\fBvoid\fP)"

.SS "\fBvoid\fP GLUI_Rotation::setup_texture (\fBvoid\fP)"

.SH "Member Data Documentation"
.PP 
.SS "Arcball* GLUI_Rotation::ball"

.PP
Definition at line 2439 of file glui\&.h\&.
.SS "bool GLUI_Rotation::can_spin"

.PP
Definition at line 2441 of file glui\&.h\&.
.SS "float GLUI_Rotation::damping"

.PP
Definition at line 2442 of file glui\&.h\&.
.SS "GLUquadricObj* GLUI_Rotation::quadObj"

.PP
Definition at line 2440 of file glui\&.h\&.
.SS "bool GLUI_Rotation::spinning"

.PP
Definition at line 2441 of file glui\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
