.TH "Interval" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Interval \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Window\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInterval\fP (double \fBleft\fP, double \fBright\fP)"
.br
.ti -1c
.RI "bool \fBSet\fP (double \fBleft\fP, double \fBright\fP)"
.br
.ti -1c
.RI "double \fBGetLeft\fP () const "
.br
.ti -1c
.RI "double \fBGetRight\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file Window\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Interval::Interval (doubleleft, doubleright)\fC [inline]\fP"

.PP
Definition at line 13 of file Window\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "double Interval::GetLeft () const\fC [inline]\fP"

.PP
Definition at line 29 of file Window\&.h\&.
.SS "double Interval::GetRight () const\fC [inline]\fP"

.PP
Definition at line 33 of file Window\&.h\&.
.SS "bool Interval::Set (doubleleft, doubleright)\fC [inline]\fP"

.PP
Definition at line 18 of file Window\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
