.TH "KernelData" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KernelData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CSpiceUtil\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::string\fP \fBfilename\fP"
.br
.ti -1c
.RI "\fBstd::string\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBstd::string\fP \fBsource\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file CSpiceUtil\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBstd::string\fP KernelData::filename"

.PP
Definition at line 41 of file CSpiceUtil\&.h\&.
.SS "\fBstd::string\fP KernelData::source"

.PP
Definition at line 43 of file CSpiceUtil\&.h\&.
.SS "\fBstd::string\fP KernelData::type"

.PP
Definition at line 42 of file CSpiceUtil\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
