.TH "Keys" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Keys \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Program\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBOOL\fP \fBkeyDown\fP [256]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file Program\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBOOL\fP Keys::keyDown[256]"

.PP
Definition at line 6 of file Program\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
