.TH "SSWC/src/Math/Quantity.cpp" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SSWC/src/Math/Quantity.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Quantity\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBpowi\fP (double \fBval\fP, \fBint\fP exp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double powi (doubleval, \fBint\fPexp)"

.PP
Definition at line 3 of file Quantity\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
