.TH "RGBc" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGBc \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glui\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBset\fP (\fBByte\fP \fBr\fP, \fBByte\fP \fBg\fP, \fBByte\fP \fBb\fP)"
.br
.ti -1c
.RI "\fBRGBc\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBRGBc\fP (\fBByte\fP \fBr\fP, \fBByte\fP \fBg\fP, \fBByte\fP \fBb\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBByte\fP \fBr\fP"
.br
.ti -1c
.RI "\fBByte\fP \fBg\fP"
.br
.ti -1c
.RI "\fBByte\fP \fBb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 80 of file glui\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RGBc::RGBc (\fBvoid\fP)\fC [inline]\fP"

.PP
Definition at line 86 of file glui\&.h\&.
.SS "RGBc::RGBc (\fBByte\fPr, \fBByte\fPg, \fBByte\fPb)\fC [inline]\fP"

.PP
Definition at line 87 of file glui\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP RGBc::set (\fBByte\fPr, \fBByte\fPg, \fBByte\fPb)\fC [inline]\fP"

.PP
Definition at line 84 of file glui\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBByte\fP RGBc::b"

.PP
Definition at line 82 of file glui\&.h\&.
.SS "\fBByte\fP RGBc::g"

.PP
Definition at line 82 of file glui\&.h\&.
.SS "\fBByte\fP RGBc::r"

.PP
Definition at line 82 of file glui\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
