.TH "SSWC/src/CSpice/SpaceObject.h" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SSWC/src/CSpice/SpaceObject.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'CSpiceCore\&.h'\fP
.br
\fC#include 'Frame\&.h'\fP
.br
\fC#include 'Date\&.h'\fP
.br
\fC#include 'Window\&.h'\fP
.br
\fC#include '\&.\&./Math/Vector3\&.h'\fP
.br
\fC#include '\&.\&./Math/Vector3T\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSpaceObject\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSSB_SPICE_ID\fP   0"
.br
.ti -1c
.RI "#define \fBSUN_SPICE_ID\fP   10"
.br
.ti -1c
.RI "#define \fBOBJECT_NAME_MAX_LENGTH\fP   128"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define OBJECT_NAME_MAX_LENGTH   128"

.PP
Definition at line 16 of file SpaceObject\&.h\&.
.SS "#define SSB_SPICE_ID   0"

.PP
Definition at line 13 of file SpaceObject\&.h\&.
.SS "#define SUN_SPICE_ID   10"

.PP
Definition at line 14 of file SpaceObject\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
