.TH "SSWC/src/CSpice/SpaceBody.h" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SSWC/src/CSpice/SpaceBody.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SpaceObject\&.h'\fP
.br
\fC#include '\&.\&./Math/Quantity\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <array>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSpaceBody\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBG\fP   6\&.67384E-11"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define G   6\&.67384E-11"

.PP
Definition at line 9 of file SpaceBody\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
