.TH "TGA" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TGA \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TGA\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTGA\fP (const char *imagePath)"
.br
.ti -1c
.RI "\fB~TGA\fP ()"
.br
.ti -1c
.RI "\fBGLuint\fP \fBgetTextureHandle\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBGLuint\fP \fBtextureHandle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file TGA\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TGA::TGA (const char *imagePath)"

.PP
Definition at line 27 of file TGA\&.cpp\&.
.SS "TGA::~TGA ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBGLuint\fP TGA::getTextureHandle (\fBvoid\fP)"

.PP
Definition at line 168 of file TGA\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBGLuint\fP TGA::textureHandle\fC [protected]\fP"

.PP
Definition at line 10 of file TGA\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
