.TH "SSWC/src/Math/Vector3.cpp" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SSWC/src/Math/Vector3.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Vector3\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBRotationMatrix\fP (float *\fBmatrix\fP, const \fBVector3\fP &axis, float \fBangle\fP)"
.br
.ti -1c
.RI "\fBVector3\fP & \fBoperator+=\fP (\fBVector3\fP &lVector, const \fBVector3\fP &rVector)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBVector3\fP& operator+= (\fBVector3\fP &lVector, const \fBVector3\fP &rVector)"

.PP
Definition at line 126 of file Vector3\&.cpp\&.
.SS "\fBvoid\fP RotationMatrix (float *matrix, const \fBVector3\fP &axis, floatangle)"

.PP
Definition at line 7 of file Vector3\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
