.TH "SSWC/src/CSpice/Window.h" 3 "Mon May 9 2016" "Version 0.1" "MissionsVisualizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SSWC/src/CSpice/Window.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CSpiceCore\&.h'\fP
.br
\fC#include 'Time\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBInterval\fP"
.br
.ti -1c
.RI "class \fBWindow\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWINDOW_MAX_INTERVALS\fP   1024"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define WINDOW_MAX_INTERVALS   1024"

.PP
Definition at line 8 of file Window\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MissionsVisualizer from the source code\&.
